import type {NormalizedQuote,QuoteProvider,QuoteRequest} from "./types";
import {fromBaseUnits,getToken,toBaseUnits} from "../token-addresses";
export const acrossProvider:QuoteProvider={name:"Across",async quote(input:QuoteRequest,signal?:AbortSignal):Promise<NormalizedQuote|null>{
 const key=process.env.ACROSS_API_KEY,integratorId=process.env.ACROSS_INTEGRATOR_ID;if(!key||!integratorId||!input.userAddress)return null;
 const from=getToken(input.fromChain,input.fromToken),to=getToken(input.toChain,input.toToken);if(!from||!to)return null;
 const params=new URLSearchParams({tradeType:"exactInput",originChainId:String(input.fromChain),destinationChainId:String(input.toChain),inputToken:from.address,outputToken:to.address,amount:toBaseUnits(input.amount,from.decimals),depositor:input.userAddress,integratorId});
 const res=await fetch("https://app.across.to/api/swap/approval?"+params,{headers:{Authorization:"Bearer "+key,accept:"application/json"},cache:"no-store",signal});if(!res.ok)return null;const q=await res.json();
 const rawOut=q?.expectedOutputAmount??q?.outputAmount??q?.quote?.outputAmount;if(!rawOut||!q?.swapTx)return null;
 return{id:"across",provider:"Across",receive:fromBaseUnits(String(rawOut),to.decimals),feeUsd:Number(q?.fees?.total?.amountUsd??q?.fees?.totalUsd??0)||undefined,etaSeconds:Number(q?.expectedFillTime||0)||undefined,steps:[String(input.fromChain),"Across",String(input.toChain)],expiresAt:new Date(Date.now()+15000).toISOString(),approvalTxs:Array.isArray(q.approvalTxns)?q.approvalTxns.map((x:any)=>({to:x.to,data:x.data,value:x.value,chainId:Number(input.fromChain)})):[],tx:{to:q.swapTx.to,data:q.swapTx.data,value:q.swapTx.value,chainId:Number(input.fromChain)},approvalPolicy:q?.checks?.allowance?{token:q.checks.allowance.token,spender:q.checks.allowance.spender,expectedAmount:String(q.checks.allowance.expected??"")}:undefined,raw:q};
}};