export type SavedTransfer={provider:string;txHash:string;sourceChainId?:number;tracking?:{orderId?:string;requestId?:string;routeId?:string};fromChain:string;toChain:string;destinationChainId?:number;fromToken:string;toToken:string;amount:string;receive:number|string;submittedAt:number;walletAddress?:string};
const KEY="crosschain-router:transfers:v1",MAX_PER_WALLET=12,MAX_STORED=60,MAX_TEXT=80,MAX_TRACKING=160;
const text=(v:unknown,max=MAX_TEXT)=>typeof v==="string"&&v.length>0&&v.length<=max;
const evmWallet=(v:unknown)=>typeof v==="string"&&/^0x[a-fA-F0-9]{40}$/.test(v);
const solanaAddress=(v:unknown)=>typeof v==="string"&&/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(v);
const wallet=(v:unknown)=>evmWallet(v)||solanaAddress(v);
const txId=(v:unknown)=>typeof v==="string"&&(/^0x[a-fA-F0-9]{64}$/.test(v)||/^[1-9A-HJ-NP-Za-km-z]{64,88}$/.test(v));
function readAllTransfers():SavedTransfer[]{if(typeof window==="undefined")return[];try{const raw=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(raw)?raw.filter(valid):[]}catch{return[]}}
const trackingValid=(v:unknown)=>v===undefined||(!!v&&typeof v==="object"&&["orderId","requestId","routeId"].every(k=>{const x=(v as Record<string,unknown>)[k];return x===undefined||text(x,MAX_TRACKING)}));
export function loadTransfers(walletAddress?:string):SavedTransfer[]{if(typeof window==="undefined"||!walletAddress||!wallet(walletAddress))return[];return readAllTransfers().filter(x=>!!x.walletAddress&&x.walletAddress.toLowerCase()===walletAddress.toLowerCase()).slice(0,MAX_PER_WALLET)}
export function saveTransfer(transfer:SavedTransfer){if(typeof window==="undefined"||!valid(transfer))return;const existing=readAllTransfers();const next=[transfer,...existing.filter(x=>x.txHash!==transfer.txHash)].slice(0,MAX_STORED);try{localStorage.setItem(KEY,JSON.stringify(next))}catch{}}
export function removeTransfer(txHash:string){if(typeof window==="undefined"||!txId(txHash))return;const existing=readAllTransfers();try{localStorage.setItem(KEY,JSON.stringify(existing.filter(x=>x.txHash!==txHash)))}catch{}}
function valid(x:unknown):x is SavedTransfer{if(!x||typeof x!=="object")return false;const v=x as Partial<SavedTransfer>;const amountValid=typeof v.amount==="string"&&v.amount.length<=80&&/^\\d+(?:\\.\\d+)?$/.test(v.amount)&&/[1-9]/.test(v.amount);const receiveValid=(typeof v.receive==="string"||typeof v.receive==="number")&&String(v.receive).length<=120&&/^\\d+(?:\\.\\d+)?$/.test(String(v.receive));return text(v.provider)&&txId(v.txHash)&&(v.sourceChainId===undefined||(Number.isSafeInteger(v.sourceChainId)&&v.sourceChainId>0))&&(v.destinationChainId===undefined||(Number.isSafeInteger(v.destinationChainId)&&v.destinationChainId>0))&&trackingValid(v.tracking)&&text(v.fromChain)&&text(v.toChain)&&text(v.fromToken,32)&&text(v.toToken,32)&&amountValid&&receiveValid&&typeof v.submittedAt==="number"&&Number.isFinite(v.submittedAt)&&v.submittedAt>0&&v.submittedAt<=Date.now()+300000&&(v.walletAddress===undefined||wallet(v.walletAddress))}
