import {NextResponse} from "next/server";import {getLiveQuotes} from "@/lib/providers";import {getSameChainQuotes,isSameChain} from "@/lib/providers/same-chain";
export const dynamic="force-dynamic";
export async function POST(request:Request){
 const body=await request.json().catch(()=>({}));const amountText=typeof body.amount==="string"?body.amount:"";if(amountText.length===0||amountText.length>80||!/^\d+(?:\.\d+)?$/.test(amountText))return NextResponse.json({error:"Invalid amount"},{status:400});if(!/[1-9]/.test(amountText))return NextResponse.json({error:"Invalid amount"},{status:400});
 const expiresAt=new Date(Date.now()+30000).toISOString();
 const userAddress=body.userAddress===undefined?undefined:String(body.userAddress);if(userAddress!==undefined&&!/^0x[a-fA-F0-9]{40}$/.test(userAddress))return NextResponse.json({error:"Invalid EVM wallet address"},{status:400});
 const input={fromChain:body.fromChain??1,toChain:body.toChain??"solana",fromToken:body.fromToken??"USDC",toToken:body.toToken??"USDC",amount:amountText,userAddress};const sameChain=isSameChain(input);
 try{const aggregate=sameChain?{quotes:await getSameChainQuotes(input),health:[]}:await getLiveQuotes(input);const live=aggregate.quotes;
 const routes=live.flatMap(q=>{const receive=String(q.receive);if(receive.length===0||receive.length>120||!/^\d+(?:\.\d+)?$/.test(receive)||!/[1-9]/.test(receive))return[];const minReceive=q.minReceive===undefined?undefined:String(q.minReceive);if(minReceive!==undefined&&(!/^\d+(?:\.\d+)?$/.test(minReceive)||!/[1-9]/.test(minReceive)))return[];const fee=typeof q.feeUsd==="number"&&Number.isFinite(q.feeUsd)&&q.feeUsd>=0?q.feeUsd:undefined;const etaSeconds=typeof q.etaSeconds==="number"&&Number.isFinite(q.etaSeconds)&&q.etaSeconds>0?q.etaSeconds:undefined;const providerExpiry=q.expiresAt?Date.parse(q.expiresAt):NaN;if(q.expiresAt&&(!Number.isFinite(providerExpiry)||providerExpiry<=Date.now()+3000))return[];const routeExpiresAt=q.expiresAt??expiresAt;const tracking=q.tracking;if(tracking!==undefined&&(typeof tracking!=="object"||tracking===null||["orderId","requestId","routeId"].some(key=>{const value=tracking[key as keyof typeof tracking];return value!==undefined&&(typeof value!=="string"||value.length===0||value.length>160)})))return[];return[{id:q.id,provider:q.provider,receive,minReceive,fee,eta:etaSeconds?formatEta(etaSeconds):"—",steps:q.steps,expiresAt:routeExpiresAt,approvalTxs:q.approvalTxs??[],tx:q.tx,tracking,capabilities:q.capabilities,routeMeta:q.routeMeta}]});if(routes.length)return NextResponse.json({mode:"live",routeType:sameChain?"swap":"cross-chain",requestedAt:new Date().toISOString(),providerHealth:aggregate.health,routes});return NextResponse.json({mode:"unavailable",routeType:sameChain?"swap":"cross-chain",requestedAt:new Date().toISOString(),providerHealth:aggregate.health,routes:[],error:sameChain?"No live same-chain swap route is currently available.":"No live cross-chain route is currently available. Check provider health or try another pair."});
 }catch(error){console.error("Live quote aggregation failed",error)}
 return NextResponse.json({mode:"unavailable",routeType:sameChain?"swap":"cross-chain",requestedAt:new Date().toISOString(),providerHealth:[],routes:[],error:sameChain?"No live same-chain swap route is currently available.":"No live cross-chain route is currently available. Try refreshing or choose another pair."});
}
function formatEta(seconds:number){return seconds<60?"~"+seconds+" sec":"~"+Math.ceil(seconds/60)+" min"}