"use client";
import {Check,Clock3,ExternalLink,LoaderCircle,TriangleAlert} from "lucide-react";
import {useTransferStatus} from "@/hooks/use-transfer-status";
import {classifyTransfer} from "@/lib/execution/rescue";
const complete=(s?:string)=>s==="filled";const failed=(s?:string)=>["expired","refunded"].includes(s||"");
export function TransactionCenter({provider,txHash}:{provider?:string;txHash?:string}){const {data,error,startedAt}=useTransferStatus(provider,txHash);if(!provider||!txHash)return null;const status=data?.status??"submitted";
 const rescue=classifyTransfer(status,startedAt);const needsRescue=["delayed","refunded","failed","unknown"].includes(rescue.state);
 const steps=[{name:"Source submitted",done:true,active:false},{name:"Bridge / solver",done:complete(status),active:!complete(status)&&!failed(status)},{name:"Destination received",done:complete(status),active:false}];
 return <section className="txCenter"><div className="txCenterHead"><span><b>Transaction Center</b><small>{provider} · tracking every 10s</small></span><em className={failed(status)?"failed":complete(status)?"done":""}>{complete(status)?"COMPLETED":failed(status)?status.toUpperCase():"IN PROGRESS"}</em></div><div className="txTimeline">{steps.map((x,i)=><div className={"txStep "+(x.done?"done ":"")+(x.active?"active":"")} key={x.name}>{x.done?<Check size={13}/>:x.active?<LoaderCircle size={13}/>:<Clock3 size={13}/>}<span><b>{x.name}</b><small>{i===0?short(txHash):i===1?status:"Waiting for destination"}</small></span></div>)}</div>{data?.destinationTxHash&&<div className="txDestination"><Check size={14}/><span>Destination transaction<b>{short(data.destinationTxHash)}</b></span></div>}{data?.refundTxHash&&<div className="txRecovery"><TriangleAlert size={14}/><span>Refund detected<b>{short(data.refundTxHash)}</b></span></div>}{needsRescue&&<div className={"rescuePanel "+rescue.state}><TriangleAlert size={15}/><span><b>{rescue.title}</b><small>{rescue.action}</small></span></div>}{data?.note&&<p className="txNote">{data.note}</p>}{error&&<p className="txNote">{error}</p>}<div className="txHashLine"><ExternalLink size={12}/><span>Source tx {short(txHash)}</span></div></section>}
function short(v:string){return v.slice(0,10)+"…"+v.slice(-8)}