"use client";
import {Check,Clock3,ExternalLink,LoaderCircle,RefreshCw,TriangleAlert} from "lucide-react";
import {useTransferStatus} from "@/hooks/use-transfer-status";
import {classifyTransfer} from "@/lib/execution/rescue";
const normalized=(s?:string)=>(s||"").toLowerCase();const complete=(s?:string)=>["filled","completed","success","succeeded"].includes(normalized(s));const failed=(s?:string)=>["expired","refunded","failed","reverted","deposit-failed"].includes(normalized(s));
const explorers:Record<number,string>={1:"https://etherscan.io/tx/",8453:"https://basescan.org/tx/",42161:"https://arbiscan.io/tx/",10:"https://optimistic.etherscan.io/tx/",137:"https://polygonscan.com/tx/",56:"https://bscscan.com/tx/"};
export function TransactionCenter({provider,txHash,sourceChainId,tracking,submittedAt,amount,receive,fromToken,toToken,onNewRoute}:{provider?:string;txHash?:string;sourceChainId?:number;tracking?:{orderId?:string;requestId?:string;routeId?:string};submittedAt?:number;amount?:string;receive?:number|string;fromToken?:string;toToken?:string;onNewRoute?:()=>void}){
 const {data,error,startedAt,refresh,refreshing}=useTransferStatus(provider,txHash,sourceChainId,tracking,submittedAt);if(!provider||!txHash)return null;const status=data?.status??"submitted";
 const rescue=classifyTransfer(status,startedAt);const needsRescue=["delayed","refunded","failed","unknown"].includes(rescue.state);const terminal=!!data?.terminal||complete(status)||failed(status);const sourceUrl=sourceChainId&&explorers[sourceChainId]?explorers[sourceChainId]+txHash:undefined;
 const steps=[{name:"Source confirmed",done:!!data?.sourceConfirmed,active:!data?.sourceConfirmed&&!data?.sourceFailed},{name:"Bridge / solver",done:complete(status),active:!data?.sourceFailed&&!complete(status)&&!failed(status)},{name:"Destination received",done:complete(status),active:false}];
 return <section className="txCenter"><div className="txCenterHead"><span><b>Transaction Center</b><small>{provider} · tracking every 10s</small></span><em className={failed(status)?"failed":complete(status)?"done":""}>{complete(status)?"COMPLETED":failed(status)?status.toUpperCase():"IN PROGRESS"}</em></div>{amount&&receive!==undefined&&<div className="txHashLine"><span>Submitted {amount} {fromToken||""} · reviewed receive {String(receive)} {toToken||""}</span></div>}<div className="txTimeline">{steps.map((x,i)=><div className={"txStep "+(x.done?"done ":"")+(x.active?"active":"")} key={x.name}>{x.done?<Check size={13}/>:x.active?<LoaderCircle size={13}/>:<Clock3 size={13}/>}<span><b>{x.name}</b><small>{i===0?(data?.sourceFailed?"Reverted":data?.sourceConfirmed?short(txHash):"Waiting for confirmation"):i===1?status:"Waiting for destination"}</small></span></div>)}</div>{data?.destinationTxHash&&<div className="txDestination"><Check size={14}/><span>Destination transaction<b>{short(data.destinationTxHash)}</b></span></div>}{data?.refundTxHash&&<div className="txRecovery"><TriangleAlert size={14}/><span>Refund detected<b>{short(data.refundTxHash)}</b></span></div>}{needsRescue&&<div className={"rescuePanel "+rescue.state}><TriangleAlert size={15}/><span><b>{rescue.title}</b><small>{rescue.action}</small></span></div>}{data?.note&&<p className="txNote">{data.note}</p>}{error&&<p className="txNote">{error}</p>}<div className="txActions">{sourceUrl&&<a href={sourceUrl} target="_blank" rel="noreferrer"><ExternalLink size={12}/> View source tx</a>}<button onClick={()=>refresh()} disabled={refreshing}><RefreshCw size={12}/>{refreshing?"Refreshing…":"Refresh status"}</button>{terminal&&onNewRoute&&<button onClick={onNewRoute}>Get a new route</button>}</div><div className="txHashLine"><ExternalLink size={12}/><span>Source tx {short(txHash)}</span></div></section>
}
function short(v:string){return v.slice(0,10)+"…"+v.slice(-8)}
