"use client";
import {createContext,useCallback,useContext,useEffect,useRef,useState} from "react";
import {assertWalletContext} from "@/lib/execution/wallet-context";

type EvmProvider={request:(args:{method:string;params?:unknown[]})=>Promise<any>;on?:(event:string,cb:(...args:any[])=>void)=>void;removeListener?:(event:string,cb:(...args:any[])=>void)=>void;providers?:EvmProvider[];isMetaMask?:boolean;isCoinbaseWallet?:boolean;isRabby?:boolean;isBraveWallet?:boolean;isTrust?:boolean};
type WalletOption={id:string;name:string;icon?:string};
type WalletState={address?:`0x${string}`;chainId?:number;connected:boolean;connecting:boolean;error?:string;wallets:WalletOption[];selectedWallet?:WalletOption;refreshWallets:()=>void;connect:(id:string)=>Promise<void>;disconnect:()=>void;switchChain:(chainId:number)=>Promise<void>;sendTransaction:(tx:{to:string;data:string;value?:string;chainId?:number},expectedChainId:number)=>Promise<string>;call:(tx:{to:string;data:string;value?:string})=>Promise<string>;estimateGas:(tx:{to:string;data:string;value?:string})=>Promise<bigint>;getReceiptStatus:(hash:string)=>Promise<"pending"|"confirmed"|"reverted">;waitForReceipt:(hash:string,expectedChainId:number)=>Promise<void>};
const Context=createContext<WalletState|null>(null);
declare global{interface Window{ethereum?:EvmProvider}}
const ADDRESS=/^0x[a-fA-F0-9]{40}$/;
function safeIcon(value:unknown){return typeof value==="string"&&value.length<20000&&/^data:image\/(?:png|webp|jpeg|svg\+xml);base64,[A-Za-z0-9+/]+=*$/.test(value)?value:undefined}
function legacyName(provider:EvmProvider){return provider.isRabby?"Rabby":provider.isCoinbaseWallet?"Coinbase Wallet":provider.isBraveWallet?"Brave Wallet":provider.isTrust?"Trust Wallet":provider.isMetaMask?"MetaMask":"Browser wallet"}

export function WalletProvider({children}:{children:React.ReactNode}){
 const [address,setAddress]=useState<`0x${string}`>();const [chainId,setChainId]=useState<number>();const [connecting,setConnecting]=useState(false);const [error,setError]=useState<string>();const [wallets,setWallets]=useState<WalletOption[]>([]);const [selectedWallet,setSelectedWallet]=useState<WalletOption>();
 const discovered=useRef(new Map<string,{provider:EvmProvider;name:string;icon?:string}>());const active=useRef<EvmProvider|null>(null);const cleanup=useRef<()=>void>(()=>{});
 const publish=useCallback(()=>setWallets(Array.from(discovered.current,([id,{name,icon}])=>({id,name,icon}))),[]);
 const refreshWallets=useCallback(()=>{if(typeof window==="undefined")return;window.dispatchEvent(new Event("eip6963:requestProvider"));const legacy=window.ethereum?.providers?.length?window.ethereum.providers:window.ethereum?[window.ethereum]:[];
  for(const [index,provider] of legacy.entries()){if(!provider||typeof provider.request!=="function"||Array.from(discovered.current.values()).some(v=>v.provider===provider))continue;const id=`legacy:${index}`;discovered.current.set(id,{provider,name:legacyName(provider)})}publish()},[publish]);
 useEffect(()=>{const announced=(event:Event)=>{const detail=(event as CustomEvent).detail as {info?:{uuid?:string;name?:string;icon?:string};provider?:EvmProvider}|undefined;
  if(!detail?.provider||typeof detail.provider.request!=="function"||typeof detail.info?.uuid!=="string"||typeof detail.info.name!=="string"||!detail.info.name.trim())return;
  const id=detail.info.uuid;if(id.length>100||discovered.current.has(id)&&discovered.current.get(id)?.provider!==detail.provider)return;for(const [key,value] of discovered.current){if(key.startsWith("legacy:")&&value.provider===detail.provider)discovered.current.delete(key)}
  discovered.current.set(id,{provider:detail.provider,name:detail.info.name.slice(0,50),icon:safeIcon(detail.info.icon)});publish()};
  window.addEventListener("eip6963:announceProvider",announced);refreshWallets();const timer=setTimeout(refreshWallets,600);
  return()=>{clearTimeout(timer);window.removeEventListener("eip6963:announceProvider",announced);cleanup.current()};
 },[publish,refreshWallets]);
 const connect=async(id:string)=>{setError(undefined);refreshWallets();const selected=discovered.current.get(id);if(!selected){const message="Wallet is no longer available. Refresh the list.";setError(message);throw new Error(message)}setConnecting(true);
  try{const accounts=await selected.provider.request({method:"eth_requestAccounts"});const chain=await selected.provider.request({method:"eth_chainId"});if(!ADDRESS.test(accounts?.[0]??"")||!Number.isSafeInteger(Number(chain)))throw new Error("Wallet returned an invalid account or network");
   cleanup.current();const provider=selected.provider;const onAccounts=(values:string[])=>{setAddress(ADDRESS.test(values?.[0]??"")?values[0] as `0x${string}`:undefined);if(!ADDRESS.test(values?.[0]??""))setSelectedWallet(undefined)};const onChain=(value:string)=>setChainId(Number(value));provider.on?.("accountsChanged",onAccounts);provider.on?.("chainChanged",onChain);
   cleanup.current=()=>{provider.removeListener?.("accountsChanged",onAccounts);provider.removeListener?.("chainChanged",onChain)};active.current=provider;setAddress(accounts[0]);setChainId(Number(chain));setSelectedWallet({id,name:selected.name,icon:selected.icon});
  }catch(e){const message=e instanceof Error?e.message:"Wallet connection failed";setError(message);throw e}finally{setConnecting(false)}};
 const disconnect=()=>{cleanup.current();cleanup.current=()=>{};active.current=null;setAddress(undefined);setChainId(undefined);setSelectedWallet(undefined);setError(undefined)};
 const requireProvider=()=>{if(!active.current)throw new Error("Choose and connect a wallet first");return active.current};
 const switchChain=async(id:number)=>{const provider=requireProvider(),target="0x"+id.toString(16);try{await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:target}]})}catch(error){const code=(error as {code?:number})?.code;if(code!==4902)throw error;const networks:Record<number,{chainName:string;rpcUrls:string[];blockExplorerUrls:string[];nativeCurrency:{name:string;symbol:string;decimals:number}}>= {
  43114:{chainName:"Avalanche C-Chain",rpcUrls:["https://api.avax.network/ext/bc/C/rpc"],blockExplorerUrls:["https://snowtrace.io"],nativeCurrency:{name:"Avalanche",symbol:"AVAX",decimals:18}},
  59144:{chainName:"Linea",rpcUrls:["https://rpc.linea.build"],blockExplorerUrls:["https://lineascan.build"],nativeCurrency:{name:"Ether",symbol:"ETH",decimals:18}},
  4663:{chainName:"Robinhood Chain",rpcUrls:["https://rpc.mainnet.chain.robinhood.com"],blockExplorerUrls:["https://robinhoodchain.blockscout.com"],nativeCurrency:{name:"Ether",symbol:"ETH",decimals:18}}
 };if(!networks[id])throw error;await provider.request({method:"wallet_addEthereumChain",params:[{chainId:target,...networks[id]}]});await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:target}]})}setChainId(id)};
 const sendTransaction=async(tx:{to:string;data:string;value?:string;chainId?:number},expectedChainId:number)=>{const provider=requireProvider();if(!address)throw new Error("Connect wallet first");const [currentChain,accounts]=await Promise.all([provider.request({method:"eth_chainId"}),provider.request({method:"eth_accounts"})]);assertWalletContext(currentChain,accounts,expectedChainId,address,tx.chainId);const hash=await provider.request({method:"eth_sendTransaction",params:[{from:address,to:tx.to,data:tx.data,value:tx.value||"0x0",chainId:"0x"+expectedChainId.toString(16)}]});if(typeof hash!=="string"||!/^0x[a-fA-F0-9]{64}$/.test(hash))throw new Error("Wallet did not return a valid transaction hash. Check wallet activity before retrying.");return hash};
 const call=async(tx:{to:string;data:string;value?:string})=>{const provider=requireProvider();if(!address)throw new Error("Connect wallet first");return await provider.request({method:"eth_call",params:[{from:address,to:tx.to,data:tx.data,value:tx.value||"0x0"},"latest"]})};
 const estimateGas=async(tx:{to:string;data:string;value?:string})=>{const provider=requireProvider();if(!address)throw new Error("Connect wallet first");const value=await provider.request({method:"eth_estimateGas",params:[{from:address,to:tx.to,data:tx.data,value:tx.value||"0x0"}]});return BigInt(value)};
 const getReceiptStatus=async(hash:string):Promise<"pending"|"confirmed"|"reverted">=>{const provider=requireProvider();if(!/^0x[a-fA-F0-9]{64}$/.test(hash))throw new Error("Transaction hash unavailable");const receipt=await provider.request({method:"eth_getTransactionReceipt",params:[hash]});return !receipt?"pending":receipt.status==="0x1"?"confirmed":receipt.status==="0x0"?"reverted":"pending"};
 const waitForReceipt=async(hash:string,expectedChainId:number)=>{const provider=requireProvider(),deadline=Date.now()+180000;while(Date.now()<deadline){if(Number(await provider.request({method:"eth_chainId"}))!==expectedChainId)throw new Error("Wallet network changed while waiting for confirmation. Check the submitted approval on its source chain.");let timer:ReturnType<typeof setTimeout>|undefined;try{const remaining=deadline-Date.now();if(remaining<=0)break;const receipt=await Promise.race([provider.request({method:"eth_getTransactionReceipt",params:[hash]}),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error("Wallet RPC receipt check timed out")),Math.min(8000,remaining))})]);if(receipt){if(receipt.status==="0x0")throw new Error("Transaction reverted");if(receipt.status==="0x1")return;throw new Error("Wallet returned a receipt with unknown status")}}catch(e){if(Date.now()>=deadline)break;if(e instanceof Error&&e.message!=="Wallet RPC receipt check timed out")throw e}finally{if(timer)clearTimeout(timer)}const remaining=deadline-Date.now();if(remaining>0)await new Promise(r=>setTimeout(r,Math.min(2000,remaining)))}throw new Error("Transaction confirmation timed out")};
 return <Context.Provider value={{address,chainId,connected:!!address,connecting,error,wallets,selectedWallet,refreshWallets,connect,disconnect,switchChain,sendTransaction,call,estimateGas,getReceiptStatus,waitForReceipt}}>{children}</Context.Provider>
}
export function useWallet(){const v=useContext(Context);if(!v)throw new Error("useWallet must be used inside WalletProvider");return v}
export function shortAddress(address?:string){return address?address.slice(0,6)+"…"+address.slice(-4):""}
