"use client";
import {createContext,useCallback,useContext,useEffect,useState} from "react";
type WalletState={address?:`0x${string}`;chainId?:number;connected:boolean;connecting:boolean;error?:string;connect:()=>Promise<void>;disconnect:()=>void;switchChain:(chainId:number)=>Promise<void>;sendTransaction:(tx:{to:string;data:string;value?:string})=>Promise<string>;call:(tx:{to:string;data:string;value?:string})=>Promise<string>;estimateGas:(tx:{to:string;data:string;value?:string})=>Promise<bigint>;getReceiptStatus:(hash:string)=>Promise<"pending"|"confirmed"|"reverted">;waitForReceipt:(hash:string)=>Promise<void>};
const Context=createContext<WalletState|null>(null);
declare global{interface Window{ethereum?:{request:(args:{method:string;params?:unknown[]})=>Promise<any>;on?:(event:string,cb:(...args:any[])=>void)=>void;removeListener?:(event:string,cb:(...args:any[])=>void)=>void}}}
export function WalletProvider({children}:{children:React.ReactNode}){const [address,setAddress]=useState<`0x${string}`>();const [chainId,setChainId]=useState<number>();const [connecting,setConnecting]=useState(false);const [error,setError]=useState<string>();
 const sync=useCallback(async()=>{if(!window.ethereum)return;const accounts=await window.ethereum.request({method:"eth_accounts"});const chain=await window.ethereum.request({method:"eth_chainId"});setAddress(accounts?.[0]);setChainId(Number(chain))},[]);
 useEffect(()=>{sync();const accounts=(a:string[])=>setAddress(a?.[0] as `0x${string}`|undefined);const chain=(id:string)=>setChainId(Number(id));window.ethereum?.on?.("accountsChanged",accounts);window.ethereum?.on?.("chainChanged",chain);return()=>{window.ethereum?.removeListener?.("accountsChanged",accounts);window.ethereum?.removeListener?.("chainChanged",chain)}},[sync]);
 const connect=async()=>{setError(undefined);if(!window.ethereum){setError("No EVM wallet detected");return}setConnecting(true);try{const accounts=await window.ethereum.request({method:"eth_requestAccounts"});const chain=await window.ethereum.request({method:"eth_chainId"});setAddress(accounts?.[0]);setChainId(Number(chain))}catch(e){setError(e instanceof Error?e.message:"Wallet connection failed")}finally{setConnecting(false)}};
 const disconnect=()=>setAddress(undefined);
 const switchChain=async(id:number)=>{if(!window.ethereum)throw new Error("No EVM wallet detected");await window.ethereum.request({method:"wallet_switchEthereumChain",params:[{chainId:"0x"+id.toString(16)}]});setChainId(id)};
 const sendTransaction=async(tx:{to:string;data:string;value?:string})=>{if(!window.ethereum||!address)throw new Error("Connect wallet first");return await window.ethereum.request({method:"eth_sendTransaction",params:[{from:address,to:tx.to,data:tx.data,value:tx.value||"0x0"}]})};
 const call=async(tx:{to:string;data:string;value?:string})=>{if(!window.ethereum||!address)throw new Error("Connect wallet first");return await window.ethereum.request({method:"eth_call",params:[{from:address,to:tx.to,data:tx.data,value:tx.value||"0x0"},"latest"]})};
 const estimateGas=async(tx:{to:string;data:string;value?:string})=>{if(!window.ethereum||!address)throw new Error("Connect wallet first");const value=await window.ethereum.request({method:"eth_estimateGas",params:[{from:address,to:tx.to,data:tx.data,value:tx.value||"0x0"}]});return BigInt(value)};
 const getReceiptStatus=async(hash:string):Promise<"pending"|"confirmed"|"reverted">=>{if(!window.ethereum||!/^0x[a-fA-F0-9]{64}$/.test(hash))throw new Error("Wallet or transaction hash unavailable");const receipt=await window.ethereum.request({method:"eth_getTransactionReceipt",params:[hash]});return !receipt?"pending":receipt.status==="0x1"?"confirmed":receipt.status==="0x0"?"reverted":"pending"};
 const waitForReceipt=async(hash:string)=>{if(!window.ethereum)throw new Error("No EVM wallet detected");const deadline=Date.now()+180000;while(Date.now()<deadline){let timer:ReturnType<typeof setTimeout>|undefined;try{const remaining=deadline-Date.now();if(remaining<=0)break;const receipt=await Promise.race([window.ethereum.request({method:"eth_getTransactionReceipt",params:[hash]}),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error("Wallet RPC receipt check timed out")),Math.min(8000,remaining))})]);if(receipt){if(receipt.status==="0x0")throw new Error("Transaction reverted");return}}catch(e){if(Date.now()>=deadline)break;if(e instanceof Error&&e.message!=="Wallet RPC receipt check timed out")throw e}finally{if(timer)clearTimeout(timer)}const remaining=deadline-Date.now();if(remaining>0)await new Promise(r=>setTimeout(r,Math.min(2000,remaining)))}throw new Error("Transaction confirmation timed out")};
 return <Context.Provider value={{address,chainId,connected:!!address,connecting,error,connect,disconnect,switchChain,sendTransaction,call,estimateGas,getReceiptStatus,waitForReceipt}}>{children}</Context.Provider>}
export function useWallet(){const v=useContext(Context);if(!v)throw new Error("useWallet must be used inside WalletProvider");return v}
export function shortAddress(address?:string){return address?address.slice(0,6)+"…"+address.slice(-4):""}
