import type {NormalizedQuote} from "../providers/types";
export type RoutePreference="best-return"|"fastest"|"lowest-fee";
type Comparable={receive:number|string;fee?:number;eta:string};
const decimalParts=(value:number|string)=>{const text=String(value);if(!/^\d+(?:\.\d+)?$/.test(text))return null;const [whole,fraction=""]=text.split(".");return{whole:whole.replace(/^0+(?=\d)/,""),fraction:fraction.replace(/0+$/,"")}};
const compareReceive=(a:number|string,b:number|string)=>{const x=decimalParts(a),y=decimalParts(b);if(!x&&!y)return 0;if(!x)return-1;if(!y)return 1;if(x.whole.length!==y.whole.length)return x.whole.length>y.whole.length?1:-1;if(x.whole!==y.whole)return x.whole>y.whole?1:-1;const width=Math.max(x.fraction.length,y.fraction.length),xf=x.fraction.padEnd(width,"0"),yf=y.fraction.padEnd(width,"0");return xf===yf?0:xf>yf?1:-1};
const decimalDifference=(a:number|string,b:number|string,places=4)=>{const x=decimalParts(a),y=decimalParts(b);if(!x||!y)return null;const scale=Math.max(x.fraction.length,y.fraction.length),xi=BigInt(x.whole)*10n**BigInt(scale)+BigInt(x.fraction.padEnd(scale,"0")||"0"),yi=BigInt(y.whole)*10n**BigInt(scale)+BigInt(y.fraction.padEnd(scale,"0")||"0"),d=xi>=yi?xi-yi:yi-xi,base=10n**BigInt(scale),whole=d/base,fraction=(d%base).toString().padStart(scale,"0").slice(0,places).replace(/0+$/,"");return fraction?whole+"."+fraction:whole.toString()};
const etaSeconds=(eta:string)=>{const match=eta.match(/[\d.]+/);if(!match)return Number.MAX_SAFE_INTEGER;const n=Number(match[0]);if(!Number.isFinite(n)||n<=0)return Number.MAX_SAFE_INTEGER;return /min/i.test(eta)?n*60:n};
export function rankUiQuotes<T extends Comparable>(quotes:T[],preference:RoutePreference){return [...quotes].sort((a,b)=>{if(preference==="fastest")return etaSeconds(a.eta)-etaSeconds(b.eta);if(preference==="lowest-fee"){const aKnown=typeof a.fee==="number"&&Number.isFinite(a.fee)&&a.fee>=0;const bKnown=typeof b.fee==="number"&&Number.isFinite(b.fee)&&b.fee>=0;if(aKnown!==bKnown)return aKnown?-1:1;if(!aKnown&&!bKnown)return compareReceive(b.receive,a.receive);return a.fee!-b.fee!}return compareReceive(b.receive,a.receive)})}
export function routeReason<T extends Comparable>(quote:T,quotes:T[],preference:RoutePreference){if(!quotes.length)return "";if(preference==="fastest"){const currentEta=etaSeconds(quote.eta);if(currentEta===Number.MAX_SAFE_INTEGER)return "Quoted ETA unavailable for this route.";const known=quotes.filter(q=>etaSeconds(q.eta)!==Number.MAX_SAFE_INTEGER).sort((a,b)=>etaSeconds(a.eta)-etaSeconds(b.eta));const next=known[1];return next?"Fastest quoted route · about "+Math.max(0,etaSeconds(next.eta)-currentEta)+"s quicker than the next option.":"Fastest quoted route."}if(preference==="lowest-fee"){const fee=quote.fee;if(typeof fee!=="number"||!Number.isFinite(fee)||fee<0)return "Quoted fee unavailable for this route.";const known=quotes.filter(q=>typeof q.fee==="number"&&Number.isFinite(q.fee)&&q.fee>=0).sort((a,b)=>a.fee!-b.fee!);const next=known[1];return next?"Lowest quoted cost · saves about $"+Math.max(0,next.fee!-fee).toFixed(2)+" versus the next option.":"Lowest quoted cost."}const next=[...quotes].sort((a,b)=>compareReceive(b.receive,a.receive))[1];const difference=next?decimalDifference(quote.receive,next.receive,4):null;return next&&difference!==null?"Best return · delivers about "+difference+" more destination tokens than the next option.":"Best destination return."}
export function rankQuotes(quotes:NormalizedQuote[],preference:RoutePreference){return [...quotes].sort((a,b)=>{if(preference==="fastest"){const aEta=typeof a.etaSeconds==="number"&&Number.isFinite(a.etaSeconds)&&a.etaSeconds>0?a.etaSeconds:Number.MAX_SAFE_INTEGER;const bEta=typeof b.etaSeconds==="number"&&Number.isFinite(b.etaSeconds)&&b.etaSeconds>0?b.etaSeconds:Number.MAX_SAFE_INTEGER;return aEta-bEta}if(preference==="lowest-fee"){const aFee=typeof a.feeUsd==="number"&&Number.isFinite(a.feeUsd)&&a.feeUsd>=0?a.feeUsd:Number.MAX_SAFE_INTEGER;const bFee=typeof b.feeUsd==="number"&&Number.isFinite(b.feeUsd)&&b.feeUsd>=0?b.feeUsd:Number.MAX_SAFE_INTEGER;return aFee-bFee}return compareReceive(b.receive,a.receive)})}
export function quoteIsStale(quote:NormalizedQuote,now=Date.now()){if(!quote.expiresAt)return false;const expires=Date.parse(quote.expiresAt);return !Number.isFinite(expires)||expires<=now}