"use client";
import {useCallback,useEffect,useRef,useState} from "react";
export type TransferStatus={provider:string;status:string;terminal:boolean;sourceConfirmed?:boolean;sourceFailed?:boolean;destinationTxHash?:string|null;refundTxHash?:string|null;note?:string};
export function useTransferStatus(provider?:string,txHash?:string,sourceChainId?:number,tracking?:{orderId?:string;requestId?:string;routeId?:string},initialStartedAt?:number){
 const startedAtRef=useRef(Date.now());const [data,setData]=useState<TransferStatus|null>(null);const [error,setError]=useState<string>();const [refreshing,setRefreshing]=useState(false);
 useEffect(()=>{startedAtRef.current=initialStartedAt&&Number.isFinite(initialStartedAt)?initialStartedAt:Date.now();setData(null);setError(undefined)},[provider,txHash,initialStartedAt]);
 const check=useCallback(async()=>{if(!provider||!txHash)return;setRefreshing(true);const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),9000);try{const r=await fetch("/api/status?provider="+encodeURIComponent(provider)+"&txHash="+encodeURIComponent(txHash)+(sourceChainId?"&sourceChainId="+sourceChainId:"")+(tracking?.orderId?"&orderId="+encodeURIComponent(tracking.orderId):"")+(tracking?.requestId?"&requestId="+encodeURIComponent(tracking.requestId):""),{cache:"no-store",signal:controller.signal});if(!r.ok)throw new Error("Status check failed");setData(await r.json());setError(undefined)}catch(e){if(controller.signal.aborted){setError("Status check timed out. Try again.");return}setError(e instanceof Error?e.message:"Status check failed")}finally{clearTimeout(timeout);setRefreshing(false)}},[provider,txHash,sourceChainId,tracking?.orderId,tracking?.requestId]);
 useEffect(()=>{if(!provider||!txHash)return;let active=true;let controller:AbortController|undefined;let running=false;const run=async()=>{if(running)return;running=true;controller=new AbortController();const timeout=setTimeout(()=>controller?.abort(),9000);try{const r=await fetch("/api/status?provider="+encodeURIComponent(provider)+"&txHash="+encodeURIComponent(txHash)+(sourceChainId?"&sourceChainId="+sourceChainId:"")+(tracking?.orderId?"&orderId="+encodeURIComponent(tracking.orderId):"")+(tracking?.requestId?"&requestId="+encodeURIComponent(tracking.requestId):""),{cache:"no-store",signal:controller.signal});if(!r.ok)throw new Error("Status check failed");const next=await r.json();if(active){setData(next);setError(undefined)}}catch(e){if(active&&!(e instanceof DOMException&&e.name==="AbortError"))setError(e instanceof Error?e.message:"Status check failed")}finally{clearTimeout(timeout)}};
 run();const timer=setInterval(()=>{if(!data?.terminal)run()},10000);return()=>{active=false;controller?.abort();clearInterval(timer)}},[provider,txHash,sourceChainId,tracking?.orderId,tracking?.requestId,data?.terminal]);
 return{data,error,startedAt:startedAtRef.current,refresh:check,refreshing};
}
